name: cloud-run-deploy
env:
  PROJECT_ID: run-app-341001
  SERVICE: default
  REGION: asia-northeast1
  IMAGE: asia.gcr.io/run-app-341001/goapi:latest

on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout The Repository
        uses: actions/checkout@v2
      - name: Auth By Using OIDC ID Token
        id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: 'projects/run-app-341001/locations/global/workloadIdentityPools/github-actions-pool/providers/workload-identiry-provider'
          service_account: '"cloud-workload-identity-sa@run-app-341001.iam.gserviceaccount.com'
      - name: Authorize Docker push
        run: gcloud auth configure-docker
      - name: Build and Deploy a docker image
        run: sh push-gcr.sh
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0.4.0
        with:
          service: ${{ env.SERVICE }}
          image: ${{ env.IMAGE }}
          region: ${{ env.REGION }}
